# Generated by Django 4.2.9 on 2024-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='Não informado', max_length=8),
        ),
    ]
