# Generated by Django 4.2.9 on 2024-11-29 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_post_image_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
